import type { SxProps, Theme } from '@mui/material/styles';

import { colorTokens, radiusTokens, spacingTokens, typographyTokens } from './tokens';

const heroOverlayPattern = `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.06'%3E%3Cpath d='m36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`;

const datesGroupPageStyles = {
  main: {
    role: 'main',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.neutral[50]} 0%, rgba(244, 185, 66, 0.18) 100%)`,
  } satisfies SxProps<Theme>,
  mobilePage: {
    display: { xs: 'flex', md: 'none' },
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(160deg, ${colorTokens.neutral[50]} 0%, rgba(253, 244, 220, 0.95) 28%, rgba(250, 238, 222, 0.85) 100%)`,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: 'rgba(255,255,255,0.95)',
    backdropFilter: 'blur(14px)',
    borderBottom: '1px solid rgba(210, 195, 176, 0.45)',
    boxShadow: '0 16px 32px rgba(61, 48, 36, 0.12)',
  } satisfies SxProps<Theme>,
  mobileHeaderBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.sm,
    borderRadius: radiusTokens.md,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    boxShadow: '0 18px 36px rgba(238, 92, 40, 0.28)',
  } satisfies SxProps<Theme>,
  mobileHeaderTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 18,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.earth[800]} 0%, ${colorTokens.safari[700]} 85%)`,
    WebkitBackgroundClip: 'text',
    color: 'transparent',
  } satisfies SxProps<Theme>,
  mobileHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderButton: {
    width: 40,
    height: 40,
    borderRadius: radiusTokens.md,
    border: 'none',
    backgroundColor: 'transparent',
    color: 'rgba(74,57,42,0.75)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(245,243,240,0.85)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '2px solid rgba(238, 92, 40, 0.25)',
    boxShadow: '0 16px 32px rgba(61, 48, 36, 0.16)',
  } satisfies SxProps<Theme>,
  mobileMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    backgroundImage: `linear-gradient(145deg, rgba(248, 245, 236, 0.9) 0%, rgba(255, 247, 229, 0.95) 100%)`,
  } satisfies SxProps<Theme>,
  mobileSection: {
    padding: '20px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileHeroSection: {
    position: 'relative',
    height: 210,
    overflow: 'hidden',
    borderBottomLeftRadius: radiusTokens.lg,
    borderBottomRightRadius: radiusTokens.lg,
  } satisfies SxProps<Theme>,
  mobileHeroMedia: {
    position: 'absolute',
    inset: 0,
  } satisfies SxProps<Theme>,
  mobileHeroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobileHeroOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(115deg, rgba(0,0,0,0.68) 0%, rgba(0,0,0,0.42) 55%, rgba(0,0,0,0.12) 100%)',
  } satisfies SxProps<Theme>,
  mobileHeroContent: {
    position: 'relative',
    height: '100%',
    display: 'flex',
    alignItems: 'start',
    padding: '0 18px',
    color: colorTokens.neutral.white,
    flexDirection: 'column',
    justifyContent: 'center',
    textAlign: 'left',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileHeroTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 28,
    lineHeight: 1.15,
  } satisfies SxProps<Theme>,
  mobileHeroDescription: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.88)',
  } satisfies SxProps<Theme>,
  mobileHeroHighlights: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: spacingTokens.xs,
    width: '100%',
  } satisfies SxProps<Theme>,
  mobileHeroHighlight: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 14px',
    borderRadius: radiusTokens.lg,
    backgroundColor: 'rgba(255,255,255,0.18)',
    backdropFilter: 'blur(10px)',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileWizardSection: {
    padding: '24px 16px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileProgressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 12,
    color: 'rgba(87, 69, 54, 0.65)',
  } satisfies SxProps<Theme>,
  mobileProgressSteps: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    flexWrap: 'wrap',
  } satisfies SxProps<Theme>,
  mobileProgressStep: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileProgressNode: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 600,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.24)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileProgressNodeCompleted: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileProgressNodeActive: {
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    border: `2px solid ${colorTokens.safari[500]}`,
  } satisfies SxProps<Theme>,
  mobileProgressNodeUpcoming: {
    backgroundColor: 'rgba(210, 195, 176, 0.45)',
    color: 'rgba(74,57,42,0.65)',
  } satisfies SxProps<Theme>,
  mobileProgressLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: 'rgba(74,57,42,0.72)',
  } satisfies SxProps<Theme>,
  mobileProgressConnector: {
    width: 48,
    height: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(210,195,176,0.45)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  mobileProgressConnectorFilled: {
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileProgressConnectorPartial: {
    width: '55%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileSelectionCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.45)',
    boxShadow: '0 28px 60px rgba(61, 48, 36, 0.16)',
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSelectionHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSelectionTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 24,
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileSelectionSubtitle: {
    fontSize: 13,
    color: 'rgba(74,57,42,0.68)',
  } satisfies SxProps<Theme>,
  mobileSelectionBadge: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: radiusTokens.lg,
    border: '1px solid rgba(238, 92, 40, 0.25)',
    backgroundColor: 'rgba(255, 244, 236, 0.9)',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  mobileOptionGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileOptionCard: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    padding: '16px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.5)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
  } satisfies SxProps<Theme>,
  mobileOptionCardActive: {
    borderColor: colorTokens.safari[400],
    boxShadow: '0 18px 32px rgba(238, 92, 40, 0.16)',
    transform: 'translateY(-2px)',
  } satisfies SxProps<Theme>,
  mobileOptionRadio: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: '2px solid rgba(214, 198, 178, 0.75)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  } satisfies SxProps<Theme>,
  mobileOptionRadioActive: {
    borderColor: colorTokens.safari[500],
    '&::after': {
      content: '""',
      width: 10,
      height: 10,
      borderRadius: '50%',
      backgroundColor: colorTokens.safari[500],
    },
  } satisfies SxProps<Theme>,
  mobileSeasonalCard: {
    backgroundImage: 'linear-gradient(135deg, rgba(255, 243, 209, 0.85) 0%, rgba(254, 229, 167, 0.8) 100%)',
    borderRadius: 1,
    border: '1px solid rgba(254, 215, 170, 0.6)',
    padding: 3,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSeasonalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'start',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSeasonalIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'start',
    padding: spacingTokens.xs,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(255,255,255,0.32)',
    color: '#b45309',
  } satisfies SxProps<Theme>,
  mobileSeasonalList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSeasonalItem: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileFooter: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 1,
    borderTop: '1px solid rgba(214,198,178,0.45)',
    paddingTop: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileFooterBackButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 14px',
    borderRadius: radiusTokens.lg,
    border: 'none',
    backgroundColor: 'transparent',
    color: 'rgba(74,57,42,0.7)',
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  mobileFooterActionRow: {
    display: 'flex',
    gap: spacingTokens.xs,
    justifyContent: 'flex-start',
  } satisfies SxProps<Theme>,
  mobileFooterSecondaryButton: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 16px',
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    color: 'rgba(74,57,42,0.75)',
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  mobileFooterPrimaryButton: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 18px',
    borderRadius: 1,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    boxShadow: '0 18px 32px rgba(238, 92, 40, 0.22)',
  } satisfies SxProps<Theme>,
  mobileTipsSection: {
    padding: '32px 16px 64px',
    backgroundImage: 'linear-gradient(145deg, rgba(248, 245, 235, 0.75) 0%, rgba(253, 244, 220, 0.85) 100%)',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileTipsHeader: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileTipsTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 26,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileTipsSubtitle: {
    fontSize: 14,
    color: 'rgba(74,57,42,0.68)',
  } satisfies SxProps<Theme>,
  mobileTipList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileTipCard: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 2,
    border: '1px solid rgba(214,198,178,0.45)',
    boxShadow: '0 24px 52px rgba(61, 48, 36, 0.16)',
    padding: 3,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    alignItems: 'center',
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  mobileTipIconWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.xs,
    borderRadius: radiusTokens.lg,
    backgroundColor: 'rgba(239, 219, 167, 0.35)',
  } satisfies SxProps<Theme>,
  mobileTipTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 600,
    fontSize: 20,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileTipItems: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    width: '100%',
    textAlign: 'left',
  } satisfies SxProps<Theme>,
  mobileTipItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: 'rgba(74,57,42,0.78)',
  } satisfies SxProps<Theme>,
  heroSection: {
    position: 'relative',
    height: { xs: 420, md: 320 },
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  heroMediaWrap: {
    position: 'absolute',
    inset: 0,
  } satisfies SxProps<Theme>,
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage:
      'linear-gradient(120deg, rgba(0,0,0,0.72) 0%, rgba(0,0,0,0.45) 55%, rgba(0,0,0,0.12) 100%)',
  } satisfies SxProps<Theme>,
  heroContentWrap: {
    position: 'relative',
    height: '100%',
    maxWidth: 1120,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    alignItems: 'center',
  } satisfies SxProps<Theme>,
  heroCopy: {
    maxWidth: { xs: '100%', md: 640 },
    color: colorTokens.neutral.white,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  heroTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: { xs: 36, md: 50 },
    lineHeight: 1.05,
  } satisfies SxProps<Theme>,
  heroDescription: {
    fontSize: { xs: 18, md: 20 },
    color: 'rgba(255,255,255,0.9)',
  } satisfies SxProps<Theme>,
  heroHighlights: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  heroHighlight: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 18px',
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(255,255,255,0.22)',
    backdropFilter: 'blur(12px)',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  wizardSection: {
    padding: { xs: '48px 0', md: '64px 0' },
  } satisfies SxProps<Theme>,
  wizardContainer: {
    maxWidth: '1040px',
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  progressHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: { xs: 'flex-start', md: 'center' },
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  progressSteps: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressStep: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  stepWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressNode: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.neutral.white,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.28)',
  } satisfies SxProps<Theme>,
  progressNodeCompleted: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  progressNodeActive: {
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    border: `2px solid ${colorTokens.safari[400]}`,
    boxShadow: '0 12px 28px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
  progressNodeUpcoming: {
    backgroundColor: 'rgba(210, 195, 176, 0.45)',
    color: 'rgba(74,57,42,0.6)',
  } satisfies SxProps<Theme>,
  progressLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  progressLabelActive: {
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  progressLabelCompleted: {
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  progressConnector: {
    width: 72,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(210, 195, 176, 0.55)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  progressConnectorFilled: {
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  progressConnectorPartial: {
    width: '60%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  selectionCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(210, 195, 176, 0.45)',
    backdropFilter: 'blur(18px)',
    boxShadow: '0 32px 64px rgba(61, 48, 36, 0.16)',
    padding: { xs: spacingTokens.xs, md: spacingTokens.sm },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: { xs: 'flex-start', md: 'center' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionTitleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: { xs: 30, md: 34 },
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  selectionSubtitle: {
    fontSize: 14,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  selectionBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '14px 20px',
    borderRadius: 1,
    backgroundColor: 'rgba(238, 92, 40, 0.08)',
    border: `1px solid rgba(238, 92, 40, 0.2)`,
    fontWeight: 600,
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: 'repeat(2, minmax(0, 1fr))' },
    gap: { xs: spacingTokens.xs, md: spacingTokens.xs },
  } satisfies SxProps<Theme>,
  sectionColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  sectionIntro: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  sectionTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 24,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  sectionDescription: {
    fontSize: 14,
    color: 'rgba(74,57,42,0.65)',
  } satisfies SxProps<Theme>,
  optionGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  optionCard: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '16px 20px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.6)',
    backgroundColor: 'rgba(255,255,255,0.88)',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
    cursor: 'pointer',
  } satisfies SxProps<Theme>,
  optionCardActive: {
    borderColor: colorTokens.safari[400],
    boxShadow: '0 18px 32px rgba(238, 92, 40, 0.18)',
    transform: 'translateY(-2px)',
  } satisfies SxProps<Theme>,
  optionRadio: {
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: '2px solid rgba(214, 198, 178, 0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } satisfies SxProps<Theme>,
  optionRadioActive: {
    borderColor: colorTokens.safari[500],
    '&::after': {
      content: '""',
      width: 10,
      height: 10,
      borderRadius: '50%',
      backgroundColor: colorTokens.safari[500],
    },
  } satisfies SxProps<Theme>,
  inputGroup: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  inputField: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  inputLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  inputSurface: {
    padding: '14px 16px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.75)',
    backgroundColor: 'rgba(255,255,255,0.95)',
    fontSize: 14,
    fontWeight: 500,
    color: colorTokens.earth[700],
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    '&:focus-visible': {
      borderColor: colorTokens.safari[400],
      boxShadow: '0 0 0 3px rgba(238, 92, 40, 0.18)',
    },
  } satisfies SxProps<Theme>,
  monthGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: 'repeat(2, minmax(0, 1fr))', sm: 'repeat(3, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  monthCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    padding: '5px 10px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.55)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
  } satisfies SxProps<Theme>,
  monthCardHighlight: {
    borderColor: 'rgba(34, 197, 94, 0.5)',
    backgroundColor: 'rgba(236, 252, 243, 0.9)',
    color: '#15803d',
  } satisfies SxProps<Theme>,
  monthCardSelected: {
    borderColor: colorTokens.safari[400],
    boxShadow: '0 14px 28px rgba(238, 92, 40, 0.14)',
    transform: 'translateY(-2px)',
  } satisfies SxProps<Theme>,
  seasonalCard: {
    backgroundImage: 'linear-gradient(135deg, rgba(255, 243, 209, 0.85) 0%, rgba(254, 229, 167, 0.8) 100%)',
    borderRadius: 1,
    border: '1px solid rgba(254, 215, 170, 0.6)',
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  seasonalHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  seasonalIconWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.xs,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(255,255,255,0.32)',
    color: '#b45309',
  } satisfies SxProps<Theme>,
  seasonalList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  seasonalItem: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  selectField: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.75)',
    backgroundColor: 'rgba(255,255,255,0.95)',
    fontSize: 14,
    fontWeight: 500,
    color: colorTokens.earth[700],
    cursor: 'pointer',
  } satisfies SxProps<Theme>,
  counterGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  counterCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  counterControl: {
    display: 'flex',
    alignItems: 'center',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.7)',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.9)',
  } satisfies SxProps<Theme>,
  counterButton: {
    width: 40,
    height: 40,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'rgba(74,57,42,0.65)',
    cursor: 'pointer',
  } satisfies SxProps<Theme>,
  counterButtonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  } satisfies SxProps<Theme>,
  counterValue: {
    flex: 1,
    textAlign: 'center',
    fontWeight: 600,
    color: colorTokens.earth[800],
    fontSize: 16,
  } satisfies SxProps<Theme>,
  accommodationCard: {
    display: 'flex',
    alignItems: 'start',
    gap: spacingTokens.xs,
    padding: '16px 20px',
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.88)',
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
  } satisfies SxProps<Theme>,
  checkboxGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  checkboxItem: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 16px',
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.5)',
    backgroundColor: 'rgba(255,255,255,0.85)',
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
    position: 'relative',
  } satisfies SxProps<Theme>,
  checkboxIndicator: {
    width: 18,
    height: 18,
    borderRadius: 6,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.95)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colorTokens.neutral.white,
    transition: 'background-color 0.2s ease, border-color 0.2s ease',
  } satisfies SxProps<Theme>,
  checkboxIndicatorActive: {
    backgroundColor: colorTokens.safari[500],
    borderColor: colorTokens.safari[500],
  } satisfies SxProps<Theme>,
  pillGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  pillOption: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 16px',
    borderRadius: radiusTokens.pill,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.earth[700],
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, background-color 0.2s ease, box-shadow 0.2s ease',
  } satisfies SxProps<Theme>,
  pillOptionActive: {
    backgroundColor: colorTokens.safari[500],
    borderColor: colorTokens.safari[400],
    color: colorTokens.neutral.white,
    boxShadow: '0 16px 28px rgba(238, 92, 40, 0.18)',
  } satisfies SxProps<Theme>,
  budgetSection: {
    backgroundImage: 'linear-gradient(135deg, rgba(239, 219, 167, 0.45) 0%, rgba(250, 245, 229, 0.9) 100%)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.45)',
    padding: { xs: spacingTokens.xs, md: spacingTokens.sm },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  budgetGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, minmax(0, 1fr))' },
    gap: spacingTokens.xs,

  } satisfies SxProps<Theme>,
  budgetCard: {
    backgroundColor: colorTokens.neutral.white,
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.45)',
    boxShadow: '0 16px 32px rgba(61, 48, 36, 0.12)',
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'start', 
    gap: spacingTokens.xs,
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  budgetCardFeatured: {
    border: `1px solid ${colorTokens.safari[300]}`,
    boxShadow: '0 20px 36px rgba(238, 92, 40, 0.18)',
    position: 'relative',
  } satisfies SxProps<Theme>,
  budgetTag: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(238, 92, 40, 0.12)',
    color: colorTokens.safari[700],
    fontSize: 12,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  budgetNote: {
    textAlign: 'center',
    fontSize: 12,
    color: 'rgba(74,57,42,0.65)',
  } satisfies SxProps<Theme>,
  residentCard: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
    padding: spacingTokens.xs,
    borderRadius: 2,
    border: '1px solid rgba(34, 197, 94, 0.2)',
    backgroundImage: 'linear-gradient(135deg, rgba(236, 253, 245, 0.95) 0%, rgba(209, 250, 229, 0.7) 100%)',
  } satisfies SxProps<Theme>,
  residentButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 24px',
    borderRadius: 1,
    backgroundImage: 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
    color: colorTokens.neutral.white,
    fontWeight: 600,
    boxShadow: '0 14px 28px rgba(34, 197, 94, 0.25)',
  } satisfies SxProps<Theme>,
  selectionFooter: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'stretch', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.sm,
    borderTop: '1px solid rgba(210,195,176,0.45)',
    paddingTop: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  footerButtonSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 20px',
    borderRadius: 18,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    color: 'rgba(74,57,42,0.75)',
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  footerButtonPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 28px',
    borderRadius: 20,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    boxShadow: '0 16px 30px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
  travelTipsSection: {
    padding: { xs: '56px 0', md: '72px 0' },
    backgroundImage: 'linear-gradient(135deg, rgba(248, 245, 235, 0.7) 0%, rgba(253, 244, 220, 0.8) 100%)',
  } satisfies SxProps<Theme>,
  travelTipsContainer: {
    maxWidth: 1120,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  sectionHeader: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  sectionHeaderTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: { xs: 32, md: 40 },
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  sectionHeaderSubtitle: {
    fontSize: 18,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  tipsGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tipCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.4)',
    boxShadow: '0 28px 56px rgba(61, 48, 36, 0.16)',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tipCardHeader: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  tipIconWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.sm,
    borderRadius: radiusTokens.lg,
    backgroundColor: 'rgba(239, 219, 167, 0.4)',
  } satisfies SxProps<Theme>,
  tipList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  calendarSection: {
    padding: { xs: '64px 0', md: '80px 0' },
  } satisfies SxProps<Theme>,
  calendarContainer: {
    maxWidth: 1040,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
  } satisfies SxProps<Theme>,
  calendarCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.4)',
    boxShadow: '0 32px 64px rgba(61, 48, 36, 0.16)',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  calendarHeader: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  calendarWeekHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: spacingTokens.xs,
    fontWeight: 600,
    color: 'rgba(74,57,42,0.75)',
  } satisfies SxProps<Theme>,
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  calendarDay: {
    height: 60,
    borderRadius: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    backgroundColor: 'rgba(240, 236, 229, 0.5)',
    color: 'rgba(74,57,42,0.45)',
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  calendarDayAvailable: {
    backgroundColor: 'rgba(220, 252, 231, 0.9)',
    color: '#166534',
    border: '1px solid rgba(34, 197, 94, 0.4)',
  } satisfies SxProps<Theme>,
  calendarDayPeak: {
    backgroundColor: 'rgba(254, 235, 200, 0.9)',
    color: '#b45309',
    border: '1px solid rgba(251, 191, 36, 0.4)',
  } satisfies SxProps<Theme>,
  calendarDayBooked: {
    backgroundColor: 'rgba(254, 202, 202, 0.9)',
    color: '#b91c1c',
    border: '1px solid rgba(239, 68, 68, 0.35)',
  } satisfies SxProps<Theme>,
  calendarLegend: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.md,
  } satisfies SxProps<Theme>,
  legendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  legendSwatch: {
    width: 16,
    height: 16,
    borderRadius: 4,
    border: '1px solid rgba(74,57,42,0.1)',
  } satisfies SxProps<Theme>,
  consultationSection: {
    position: 'relative',
    padding: { xs: '72px 0', md: '96px 0' },
    backgroundImage: 'linear-gradient(135deg, #3d3024 0%, #5a4433 50%, #ae311b 100%)',
    color: colorTokens.neutral.white,
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  consultationOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: heroOverlayPattern,
    opacity: 0.25,
  } satisfies SxProps<Theme>,
  consultationContainer: {
    position: 'relative',
    maxWidth: 1120,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  consultationHeader: {
    gridColumn: '1 / -1',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  consultationTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: { xs: 34, md: 40 },
    fontWeight: 700,
  } satisfies SxProps<Theme>,
  consultationSubtitle: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.8)',
  } satisfies SxProps<Theme>,
  expertCard: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 1,
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    backdropFilter: 'blur(12px)',
  } satisfies SxProps<Theme>,
  expertHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  expertAvatar: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '2px solid rgba(255,255,255,0.35)',
  } satisfies SxProps<Theme>,
  contactButtons: {
    display: 'flex',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  contactButtonPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 16px',
    borderRadius: 1,
    backgroundColor: colorTokens.safari[500],
    color: colorTokens.neutral.white,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  contactButtonSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 16px',
    borderRadius: 1,
    border: '1px solid rgba(255,255,255,0.35)',
    color: colorTokens.neutral.white,
    backgroundColor: 'rgba(255,255,255,0.12)',
  } satisfies SxProps<Theme>,
  consultationForm: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 1,
    border: '1px solid rgba(255,255,255,0.25)',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    backdropFilter: 'blur(12px)',
  } satisfies SxProps<Theme>,
  formRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0,1fr))' },
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  formField: {
    padding: '12px 16px',
    borderRadius: 1,
    border: '1px solid rgba(255,255,255,0.3)',
    backgroundColor: 'rgba(255,255,255,0.15)',
    color: colorTokens.neutral.white,
    fontSize: 14,
    fontWeight: 500,
    '&::placeholder': {
      color: 'rgba(255,255,255,0.7)',
    },
  } satisfies SxProps<Theme>,
  formTextArea: {
    minHeight: 96,
    resize: 'none',
  } satisfies SxProps<Theme>,
  formButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 20px',
    borderRadius: 1,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    boxShadow: '0 16px 30px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
} as const;

export default datesGroupPageStyles;
