import type { SxProps, Theme } from '@mui/material/styles';

import { colorTokens, radiusTokens, spacingTokens, typographyTokens } from './tokens';
import { wizardHeroSharedStyles } from './preferencesPageStyles';

const heroOverlayPattern = `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.05'%3E%3Cpath d='m36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`;

export const destinationsPageStyles = {
  main: {
    role: 'main',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(140deg, ${colorTokens.neutral[50]} 0%, rgba(244, 185, 66, 0.12) 100%)`,
  } satisfies SxProps<Theme>,
  mobilePage: {
    display: { xs: 'flex', md: 'none' },
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(160deg, ${colorTokens.neutral[50]} 0%, rgba(250, 244, 236, 0.95) 28%, rgba(248, 239, 227, 0.9) 100%)`,
  } satisfies SxProps<Theme>,
  mobileHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: 'rgba(255,255,255,0.95)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(210, 195, 176, 0.5)',
    boxShadow: '0 12px 24px rgba(61, 48, 36, 0.08)',
  } satisfies SxProps<Theme>,
  mobileHeaderBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.sm,
    borderRadius: radiusTokens.md,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    boxShadow: '0 18px 36px rgba(238, 92, 40, 0.28)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileHeaderTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 18,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.earth[800]} 0%, ${colorTokens.safari[700]} 80%)`,
    WebkitBackgroundClip: 'text',
    color: 'transparent',
  } satisfies SxProps<Theme>,
  mobileHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderButton: {
    width: 40,
    height: 40,
    borderRadius: radiusTokens.md,
    border: 'none',
    backgroundColor: 'transparent',
    color: 'rgba(74, 57, 42, 0.75)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(245, 243, 240, 0.8)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileHeaderAvatar: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '2px solid rgba(238, 92, 40, 0.25)',
    boxShadow: '0 12px 24px rgba(61, 48, 36, 0.16)',
  } satisfies SxProps<Theme>,
  mobileMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    paddingBottom: 72,
  } satisfies SxProps<Theme>,
  mobileSection: {
    padding: '16px',
  } satisfies SxProps<Theme>,
  mobileHeroSection: {
    position: 'relative',
    height: 200,
    overflow: 'hidden',
    borderBottomLeftRadius: radiusTokens.lg,
    borderBottomRightRadius: radiusTokens.lg,
  } satisfies SxProps<Theme>,
  mobileHeroMedia: {
    position: 'absolute',
    inset: 0,
  } satisfies SxProps<Theme>,
  mobileHeroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobileHeroOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(115deg, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.35) 55%, rgba(0,0,0,0.05) 100%)',
  } satisfies SxProps<Theme>,
  mobileHeroContent: {
    position: 'relative',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    padding: '0 16px',
    color: colorTokens.neutral.white,
    flexDirection: 'column',
    justifyContent: 'center',
    textAlign: 'left',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeroTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 24,
    lineHeight: 1.2,
  } satisfies SxProps<Theme>,
  mobileHeroDescription: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.88)',
  } satisfies SxProps<Theme>,
  mobileHeroPills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeroPill: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 12px',
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(255,255,255,0.2)',
    backdropFilter: 'blur(6px)',
    fontSize: 12,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  mobileWizardSection: {
    padding: '24px 16px',
  } satisfies SxProps<Theme>,
  mobileProgressSummary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacingTokens.sm,
    fontSize: 12,
    color: 'rgba(87, 69, 54, 0.65)',
  } satisfies SxProps<Theme>,
  mobileProgressRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileProgressStep: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileProgressNode: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 600,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.24)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileProgressNodeCompleted: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileProgressNodeActive: {
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    border: `2px solid ${colorTokens.safari[500]}`,
  } satisfies SxProps<Theme>,
  mobileProgressNodeUpcoming: {
    backgroundColor: 'rgba(210, 195, 176, 0.45)',
    color: 'rgba(74, 57, 42, 0.65)',
  } satisfies SxProps<Theme>,
  mobileProgressLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  mobileProgressConnector: {
    flex: 1,
    height: 4,
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(214, 198, 178, 0.6)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  mobileProgressConnectorFilled: {
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileProgressConnectorPartial: {
    width: '50%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileSelectionCard: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.4)',
    boxShadow: '0 28px 56px rgba(61, 48, 36, 0.14)',
    backdropFilter: 'blur(12px)',
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSelectionHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSelectionTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 22,
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileSelectionSubtitle: {
    fontSize: 13,
    color: 'rgba(74, 57, 42, 0.68)',
  } satisfies SxProps<Theme>,
  mobileSelectionCounter: {
    borderRadius: 1,
    border: '1px solid rgba(238, 92, 40, 0.25)',
    backgroundColor: 'rgba(238, 92, 40, 0.08)',
    padding: '10px 16px',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  mobileDestinationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileDestinationCard: {
    borderRadius: 1,
    border: '2px solid rgba(214, 198, 178, 0.45)',
    backgroundColor: colorTokens.neutral.white,
    boxShadow: '0 18px 40px rgba(61, 48, 36, 0.12)',
    display: 'flex',
    gap: spacingTokens.xs,
    overflow: 'hidden',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
    '&:hover': {
      borderColor: colorTokens.safari[400],
      boxShadow: '0 24px 48px rgba(61, 48, 36, 0.16)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileDestinationMedia: {
    position: 'relative',
    width: 110,
    height: 110,
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  mobileDestinationImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobileDestinationBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    padding: '4px 8px',
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(255,255,255,0.9)',
    backdropFilter: 'blur(6px)',
    fontSize: 11,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileDestinationInfo: {
    flex: 1,
    padding: '1px 5px',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  } satisfies SxProps<Theme>,
  mobileDestinationTitleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileDestinationTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 18,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileDestinationPrice: {
    fontSize: 13,
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileDestinationSubtitle: {
    fontSize: 12,
    color: 'rgba(74, 57, 42, 0.65)',
  } satisfies SxProps<Theme>,
  mobileDestinationMetaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    fontSize: 11,
    color: 'rgba(74, 57, 42, 0.65)',
  } satisfies SxProps<Theme>,
  mobileDestinationTagGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
  } satisfies SxProps<Theme>,
  mobileDestinationTag: {
    padding: '1px 8px',
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(238, 92, 40, 0.1)',
    color: colorTokens.safari[700],
    fontSize: 7,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  mobilePackageSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobilePackageTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 600,
    fontSize: 18,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobilePackageList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePackageCard: {
    borderRadius: 1,
    border: '2px solid rgba(214, 198, 178, 0.45)',
    backgroundColor: 'rgba(255,255,255,0.92)',
    boxShadow: '0 18px 40px rgba(61, 48, 36, 0.12)',
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePackageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } satisfies SxProps<Theme>,
  mobilePackageBadge: {
    padding: '4px 10px',
    borderRadius: radiusTokens.pill,
    fontSize: 11,
    fontWeight: 600,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobilePackageMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 12,
    color: 'rgba(74, 57, 42, 0.75)',
  } satisfies SxProps<Theme>,
  mobileSeasonalCard: {
    borderRadius: 1,
    border: '1px solid rgba(244, 185, 66, 0.45)',
    backgroundImage: 'linear-gradient(135deg, rgba(255, 248, 235, 0.95) 0%, rgba(252, 232, 181, 0.9) 100%)',
    padding: spacingTokens.xs,
    boxShadow: '0 18px 40px rgba(61, 48, 36, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSeasonalHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSeasonalGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0,1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSeasonalItem: {
    textAlign: 'center',
    backgroundColor: 'rgba(255,255,255,0.65)',
    borderRadius: 1,
    padding: spacingTokens.xs,
    boxShadow: '0 8px 16px rgba(61, 48, 36, 0.08)',
  } satisfies SxProps<Theme>,
  mobileFooterActions: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
    paddingTop: spacingTokens.xs,
    borderTop: '1px solid rgba(214, 198, 178, 0.45)',
  } satisfies SxProps<Theme>,
  mobileFooterBackButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '10px 0',
    border: 'none',
    background: 'none',
    fontWeight: 600,
    fontSize: 13,
    color: 'rgba(74, 57, 42, 0.75)',
    cursor: 'pointer',
    '&:hover': {
      color: colorTokens.earth[800],
    },
  } satisfies SxProps<Theme>,
  mobileFooterActionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileFooterSecondaryButton: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.6)',
    backgroundColor: colorTokens.neutral.white,
    fontWeight: 600,
    fontSize: 13,
    color: 'rgba(74, 57, 42, 0.8)',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(245, 243, 240, 0.85)',
      boxShadow: '0 16px 32px rgba(61, 48, 36, 0.12)',
    },
  } satisfies SxProps<Theme>,
  mobileFooterPrimaryButton: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: 1,
    border: 'none',
    width: '100%',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    boxShadow: '0 20px 40px rgba(238, 92, 40, 0.28)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 24px 48px rgba(238, 92, 40, 0.32)',
    },
  } satisfies SxProps<Theme>,
  mobileExpertSection: {
    padding: '24px 16px',
  } satisfies SxProps<Theme>,
  mobileExpertCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.earth[700]} 0%, ${colorTokens.safari[700]} 100%)`,
    color: colorTokens.neutral.white,
    borderRadius: 2,
    padding: spacingTokens.xs,
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 28px 56px rgba(45, 36, 24, 0.4)',
  } satisfies SxProps<Theme>,
  mobileExpertOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: heroOverlayPattern,
    opacity: 0.2,
  } satisfies SxProps<Theme>,
  mobileExpertContent: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileExpertList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileExpertItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: spacingTokens.xs,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 1,
    padding: spacingTokens.xs,
    border: '1px solid rgba(255,255,255,0.18)',
  } satisfies SxProps<Theme>,
  mobileExpertIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(238, 92, 40, 0.2)',
  } satisfies SxProps<Theme>,
  mobileExpertButton: {
    width: '100%',
    marginTop: spacingTokens.sm,
    borderRadius: 1,
    padding: '12px 16px',
    border: 'none',
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.earth[800],
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    boxShadow: '0 16px 32px rgba(255,255,255,0.25)',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.9)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileComparisonSection: {
    padding: '24px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileComparisonHeaderTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 18,
    fontWeight: 600,
    color: colorTokens.earth[800],
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  mobileComparisonHeaderSubtitle: {
    fontSize: 13,
    color: 'rgba(74, 57, 42, 0.7)',
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  mobileComparisonTableWrap: {
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.4)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    boxShadow: '0 18px 40px rgba(61, 48, 36, 0.12)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  mobileComparisonTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 11,
  } satisfies SxProps<Theme>,
  mobileComparisonHeadCell: {
    padding: '12px',
    fontFamily: typographyTokens.heading,
    fontWeight: 600,
    color: colorTokens.earth[800],
    backgroundImage: 'linear-gradient(135deg, rgba(255,248,235,0.95) 0%, rgba(252,232,181,0.8) 100%)',
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  mobileComparisonCell: {
    padding: '10px',
    textAlign: 'center',
    borderTop: '1px solid rgba(214, 198, 178, 0.35)',
    color: 'rgba(74, 57, 42, 0.75)',
  } satisfies SxProps<Theme>,
  mobileComparisonCellFeature: {
    textAlign: 'left',
    fontWeight: 600,
    backgroundColor: 'rgba(245, 243, 240, 0.8)',
  } satisfies SxProps<Theme>,
  heroSection: {
    position: 'relative',
    height: { xs: 440, md: 300 },
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  heroMediaWrap: {
    position: 'absolute',
    inset: 0,
  } satisfies SxProps<Theme>,
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage:
      'linear-gradient(112deg, rgba(0,0,0,0.72) 0%, rgba(0,0,0,0.45) 45%, rgba(0,0,0,0.15) 100%)',
  } satisfies SxProps<Theme>,
  heroContentWrap: {
    position: 'relative',
    height: '100%',
    maxWidth: 1120,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    alignItems: 'center',
  } satisfies SxProps<Theme>,
  heroCopy: {
    maxWidth: { xs: '100%', md: 620 },
    color: colorTokens.neutral.white,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  heroTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: { xs: 36, md: 52 },
    lineHeight: 1.1,
  } satisfies SxProps<Theme>,
  heroDescription: {
    fontSize: { xs: 18, md: 20 },
    color: 'rgba(255,255,255,0.9)',
  } satisfies SxProps<Theme>,
  heroHighlights: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  heroHighlight: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 18px',
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(255,255,255,0.2)',
    backdropFilter: 'blur(10px)',
    fontSize: 13,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  wizardSection: {
    padding: { xs: '48px 0', md: '64px 0' },
  } satisfies SxProps<Theme>,
   wizardContainer: {
    maxWidth: '1040px',
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressSteps: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressStep: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressNode: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 600,
    color: colorTokens.neutral.white,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.28)',
  } satisfies SxProps<Theme>,
  progressNodeCompleted: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  progressNodeActive: {
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    border: `2px solid ${colorTokens.safari[400]}`,
    boxShadow: '0 12px 28px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
  progressNodeUpcoming: {
    backgroundColor: 'rgba(210, 195, 176, 0.5)',
    color: 'rgba(74,57,42,0.6)',
  } satisfies SxProps<Theme>,
  progressLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  progressLabelActive: {
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  progressConnector: {
    width: 72,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(210, 195, 176, 0.55)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  progressConnectorFilled: {
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  progressConnectorPartial: {
    width: '50%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  selectionCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.45)',
    backdropFilter: 'blur(18px)',
    boxShadow: '0 32px 64px rgba(61, 48, 36, 0.16)',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionTitleGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: { xs: 30, md: 36 },
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  selectionSubtitle: {
    fontSize: 14,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  selectionBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 20px',
    borderRadius: 1,
    backgroundColor: 'rgba(238, 92, 40, 0.1)',
    border: `1px solid rgba(238, 92, 40, 0.25)`,
    fontWeight: 600,
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  destinationsGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0,1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  destinationCard: {
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: colorTokens.neutral.white,
    boxShadow: '0 28px 60px rgba(61, 48, 36, 0.14)',
    transition: 'transform 0.25s ease, box-shadow 0.25s ease, border-color 0.25s ease',
    cursor: 'pointer',
    '&:hover': {
      transform: 'translateY(-6px)',
      boxShadow: '0 36px 76px rgba(61, 48, 36, 0.22)',
      borderColor: `rgba(238, 92, 40, 0.45)`,
    },
    '&:hover img': {
      transform: 'scale(1.07)',
    },
  } satisfies SxProps<Theme>,
  destinationMedia: {
    position: 'relative',
    height: 200,
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  destinationImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.45s ease',
  } satisfies SxProps<Theme>,
  destinationOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(180deg, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.15) 60%, rgba(0,0,0,0.05) 100%)',
  } satisfies SxProps<Theme>,
  destinationBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    backdropFilter: 'blur(12px)',
    backgroundColor: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  destinationTitleBlock: {
    position: 'absolute',
    left: 24,
    bottom: 24,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  destinationTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 28,
    fontWeight: 700,
  } satisfies SxProps<Theme>,
  destinationSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.85)',
  } satisfies SxProps<Theme>,
  destinationBody: {
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  destinationMetaRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
    color: 'rgba(74,57,42,0.75)',
    fontSize: 13,
  } satisfies SxProps<Theme>,
  destinationMetaGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    flexWrap: 'wrap',
  } satisfies SxProps<Theme>,
  destinationPrice: {
    fontWeight: 700,
    color: colorTokens.earth[800],
    fontSize: 18,
  } satisfies SxProps<Theme>,
  destinationFeatureList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  destinationFeature: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 14,
    color: 'rgba(74,57,42,0.8)',
  } satisfies SxProps<Theme>,
  destinationTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  destinationTag: {
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(238, 92, 40, 0.1)',
    color: colorTokens.safari[700],
    fontSize: 12,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  packageSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  packageGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  packageCard: {
    borderRadius: 2,
    border: '2px solid rgba(238, 92, 40, 0.18)',
    padding: spacingTokens.xs,
    backgroundImage: `linear-gradient(135deg, rgba(238, 92, 40, 0.08) 0%, rgba(244, 185, 66, 0.16) 100%)`,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 24px 48px rgba(238, 92, 40, 0.22)',
    },
  } satisfies SxProps<Theme>,
  packageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } satisfies SxProps<Theme>,
  packageBadge: {
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    fontSize: 11,
    fontWeight: 700,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  packageFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: 'rgba(74,57,42,0.7)',
    fontSize: 13,
  } satisfies SxProps<Theme>,
  seasonalNotice: {
    backgroundImage: `linear-gradient(135deg, rgba(244,185,66,0.15) 0%, rgba(255,236,179,0.4) 100%)`,
    border: '1px solid rgba(244,185,66,0.4)',
    borderRadius: 2,
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  seasonalHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  seasonalGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: 'repeat(2, minmax(0,1fr))', md: 'repeat(4, minmax(0,1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  seasonalItem: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  selectionFooter: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: { xs: 'stretch', md: 'center' },
    gap: spacingTokens.xs,
    paddingTop: spacingTokens.xs,
    borderTop: '1px solid rgba(214, 198, 178, 0.6)',
  } satisfies SxProps<Theme>,
  footerButtonSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.sm,
    padding: '12px 20px',
    borderRadius: radiusTokens.lg,
    border: 'none',
    backgroundColor: 'transparent',
    fontWeight: 600,
    color: 'rgba(74,57,42,0.75)',
    cursor: 'pointer',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  footerButtonPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.sm,
    padding: '14px 28px',
    borderRadius: 999,
    border: 'none',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 22px 48px rgba(238, 92, 40, 0.32)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, background-image 0.2s ease',
    '&:hover': {
      transform: 'translateY(-2px) scale(1.01)',
      boxShadow: '0 28px 56px rgba(238, 92, 40, 0.36)',
      backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[600]} 0%, ${colorTokens.safari[700]} 100%)`,
    },
  } satisfies SxProps<Theme>,
  sectionWrap: {
    padding: { xs: '48px 0', md: '64px 0' },
  } satisfies SxProps<Theme>,
  sectionContainer: {
    maxWidth: 1160,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  sectionHeader: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    maxWidth: 760,
    margin: '0 auto',
  } satisfies SxProps<Theme>,
  sectionTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: { xs: 30, md: 40 },
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  sectionSubtitle: {
    fontSize: 18,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  highlightGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0,1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  highlightCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.45)',
    padding: spacingTokens.xs,
    boxShadow: '0 28px 60px rgba(61, 48, 36, 0.16)',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  highlightHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.md,
  } satisfies SxProps<Theme>,
  highlightIconWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 72,
    height: 72,
    borderRadius: radiusTokens.lg,
  } satisfies SxProps<Theme>,
  highlightTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 24,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  highlightRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 0',
    borderBottom: '1px solid rgba(214,198,178,0.45)',
    fontSize: 14,
    color: 'rgba(74,57,42,0.75)',
    '&:last-of-type': {
      borderBottom: 'none',
      paddingBottom: 0,
    },
  } satisfies SxProps<Theme>,
  highlightValue: {
    fontWeight: 600,
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  expertSection: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.earth[700]} 0%, ${colorTokens.safari[800]} 100%)`,
    borderRadius: 2,
    padding: { xs: spacingTokens.xs, md: spacingTokens.sm },
    color: colorTokens.neutral.white,
    position: 'relative',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  expertPattern: {
    position: 'absolute',
    inset: 0,
    backgroundImage: heroOverlayPattern,
    opacity: 0.18,
  } satisfies SxProps<Theme>,
  expertContent: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  expertCardGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, minmax(0,1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  expertCard: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 1,
    padding: spacingTokens.xs,
    backdropFilter: 'blur(12px)',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  expertIconWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    height: 64,
    borderRadius: '50%',
    backgroundColor: 'rgba(238, 92, 40, 0.35)',
    margin: '0 auto',
  } satisfies SxProps<Theme>,
  expertButton: {
    alignSelf: 'center',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.sm,
    padding: '14px 28px',
    borderRadius: 999,
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.earth[800],
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 18px 38px rgba(255,255,255,0.25)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 26px 48px rgba(255,255,255,0.3)',
    },
  } satisfies SxProps<Theme>,
  comparisonWrap: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.45)',
    boxShadow: '0 34px 68px rgba(61, 48, 36, 0.16)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  comparisonTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 14,
    color: 'rgba(74,57,42,0.75)',
  } satisfies SxProps<Theme>,
  comparisonHeadCell: {
    textAlign: 'center',
    padding: '20px 16px',
    fontFamily: typographyTokens.heading,
    fontWeight: 600,
    fontSize: 16,
    color: colorTokens.earth[800],
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[50]} 0%, rgba(244,185,66,0.22) 100%)`,
    borderBottom: '1px solid rgba(214,198,178,0.5)',
  } satisfies SxProps<Theme>,
  comparisonHeadCellFeature: {
    textAlign: 'left',
  } satisfies SxProps<Theme>,
  comparisonCell: {
    padding: '18px 16px',
    textAlign: 'center',
    borderBottom: '1px solid rgba(214,198,178,0.4)',
  } satisfies SxProps<Theme>,
  comparisonCellFeature: {
    textAlign: 'left',
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  comparisonRowAlt: {
    backgroundColor: 'rgba(245, 243, 240, 0.7)',
  } satisfies SxProps<Theme>,
  comparisonIconPositive: {
    color: '#16a34a',
    fontSize: 20,
  } satisfies SxProps<Theme>,
  comparisonIconNegative: {
    color: 'rgba(128,128,128,0.4)',
    fontSize: 20,
  } satisfies SxProps<Theme>,
};

export default destinationsPageStyles;
