import type { SxProps, Theme } from '@mui/material/styles';

import { colorTokens, radiusTokens, spacingTokens, typographyTokens } from './tokens';

const baseCardShadow = '0 24px 60px rgba(61, 48, 36, 0.16)';

export const myTripsPageStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePage: {
    display: { xs: 'flex', md: 'none' },
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(160deg, ${colorTokens.neutral[50]} 0%, rgba(250, 244, 236, 0.95) 28%, rgba(248, 239, 227, 0.9) 100%)`,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: 'rgba(255,255,255,0.95)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(210, 195, 176, 0.5)',
    boxShadow: '0 12px 24px rgba(61, 48, 36, 0.08)',
  } satisfies SxProps<Theme>,
  mobileHeaderGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 18,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.earth[800]} 0%, ${colorTokens.safari[700]} 80%)`,
    WebkitBackgroundClip: 'text',
    color: 'transparent',
  } satisfies SxProps<Theme>,
  mobileHeaderButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: radiusTokens.md,
    border: 'none',
    backgroundColor: 'transparent',
    color: 'rgba(74, 57, 42, 0.75)',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: 'rgba(245, 243, 240, 0.8)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    paddingBottom: 1,
  } satisfies SxProps<Theme>,
  mobileSection: {
    padding: '16px 16px 0',
  } satisfies SxProps<Theme>,
  mobileStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0,1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileStatCard: {
    borderRadius: 1,
    padding: 3,
    border: '1px solid rgba(214, 198, 178, 0.4)',
    textAlign: 'center',
    boxShadow: '0 12px 24px rgba(61, 48, 36, 0.08)',
  } satisfies SxProps<Theme>,
  mobileStatCardUpcoming: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[50]} 0%, rgba(255, 243, 236, 0.92) 100%)`,
  } satisfies SxProps<Theme>,
  mobileStatCardCompleted: {
    backgroundImage: 'linear-gradient(135deg, rgba(219, 242, 226, 0.95) 0%, rgba(190, 235, 210, 0.9) 100%)',
  } satisfies SxProps<Theme>,
  mobileStatCardInProgress: {
    backgroundImage: 'linear-gradient(135deg, rgba(219, 234, 254, 0.95) 0%, rgba(191, 219, 254, 0.9) 100%)',
  } satisfies SxProps<Theme>,
  mobileStatValue: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 22,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileStatLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: 'rgba(74, 57, 42, 0.65)',
  } satisfies SxProps<Theme>,
  mobileTabs: {
    backgroundColor: 'rgba(255,255,255,0.85)',
    backdropFilter: 'blur(8px)',
    borderRadius: 1,
    padding: 2,
    display: 'flex',
    gap: spacingTokens.xs,
    boxShadow: '0 16px 32px rgba(61, 48, 36, 0.1)',
  } satisfies SxProps<Theme>,
  mobileTabButton: {
    flex: 1,
    padding: '10px 12px',
    borderRadius: 2,
    border: 'none',
    backgroundColor: 'transparent',
    fontWeight: 600,
    fontSize: 13,
    color: 'rgba(74, 57, 42, 0.7)',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(245, 243, 240, 0.7)',
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  mobileTabButtonActive: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    boxShadow: '0 18px 36px rgba(238, 92, 40, 0.24)',
    transform: 'translateY(-1px)',
  } satisfies SxProps<Theme>,
  mobileTripList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileTripCard: {
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.9)',
    border: '1px solid rgba(214, 198, 178, 0.45)',
    boxShadow: '0 28px 52px rgba(61, 48, 36, 0.16)',
  } satisfies SxProps<Theme>,
  mobileTripMedia: {
    position: 'relative',
    height: 150,
  } satisfies SxProps<Theme>,
  mobileTripImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobileTripOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(180deg, rgba(0,0,0,0.65) 0%, rgba(0,0,0,0.25) 55%, rgba(0,0,0,0.05) 100%)',
  } satisfies SxProps<Theme>,
  mobileTripBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    boxShadow: '0 12px 28px rgba(0,0,0,0.25)',
  } satisfies SxProps<Theme>,
  mobileTripBadgeConfirmed: {
    backgroundImage: 'linear-gradient(135deg, rgba(16, 185, 129, 0.95) 0%, rgba(5, 150, 105, 0.85) 100%)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileTripBadgePending: {
    backgroundImage: 'linear-gradient(135deg, rgba(245, 158, 11, 0.95) 0%, rgba(217, 119, 6, 0.85) 100%)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileTripBadgeCompleted: {
    backgroundImage: 'linear-gradient(135deg, rgba(148, 137, 122, 0.95) 0%, rgba(95, 85, 72, 0.85) 100%)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileTripTopRow: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } satisfies SxProps<Theme>,
  mobileTripBottomContent: {
    position: 'absolute',
    left: 12,
    right : 12,
    bottom: 16,
    display: 'flex',
    flexDirection: 'column',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileTripOverlayTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 600,
    fontSize: 20,
    lineHeight: 1.2,
  } satisfies SxProps<Theme>,
  mobileTripOverlaySubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.82)',
  } satisfies SxProps<Theme>,
  mobileTripFavoriteButton: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    border: 'none',
    backgroundColor: 'rgba(255,255,255,0.25)',
    backdropFilter: 'blur(10px)',
    color: colorTokens.neutral.white,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, background-color 0.2s ease',
    '&:hover': {
      transform: 'scale(1.05)',
      backgroundColor: 'rgba(255,255,255,0.35)',
    },
  } satisfies SxProps<Theme>,
  mobileTripBody: {
    padding: '16px 16px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileTripSummary: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileTripSummaryContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileTripMetaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    color: 'rgba(74, 57, 42, 0.75)',
    fontSize: 12,
  } satisfies SxProps<Theme>,
  mobileTripMetaColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  } satisfies SxProps<Theme>,
  mobileTripMetaIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(238, 92, 40, 0.12)',
    color: colorTokens.safari[600],
  } satisfies SxProps<Theme>,
  mobileTripMetaList: {
    display: 'flex',
    flexDirection: 'column',
  } satisfies SxProps<Theme>,
  mobileTripMetaItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(245, 243, 240, 0.65)',
    borderRadius: radiusTokens.md,
    padding: '10px 12px',
    fontSize: 12,
    color: 'rgba(74, 57, 42, 0.75)',
  } satisfies SxProps<Theme>,
  mobileTripMetaItemLabel: {
    fontWeight: 600,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  mobileTripMetaCaption: {
    fontSize: 11,
    color: 'rgba(74, 57, 42, 0.6)',
  } satisfies SxProps<Theme>,
  mobileTripInlineLink: {
    fontSize: 11,
    fontWeight: 600,
    color: colorTokens.safari[600],
    textDecoration: 'none',
    cursor: 'pointer',
    '&:hover': {
      color: colorTokens.safari[700],
    },
  } satisfies SxProps<Theme>,
  mobileTripPriceBlock: {
    textAlign: 'right',
    minWidth: 96,
  } satisfies SxProps<Theme>,
  mobileTripPrice: {
    fontFamily: typographyTokens.heading,
    fontSize: 18,
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileTripPriceCaption: {
    fontSize: 11,
    fontWeight: 600,
    color: 'rgba(74, 57, 42, 0.6)',
  } satisfies SxProps<Theme>,
  mobileNoticeCard: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: spacingTokens.xs,
    borderRadius: 1,
    backgroundImage: 'linear-gradient(135deg, rgba(253, 230, 138, 0.45) 0%, rgba(251, 191, 36, 0.25) 100%)',
    border: '1px solid rgba(251, 191, 36, 0.5)',
  } satisfies SxProps<Theme>,
  mobileNoticeIcon: {
    width: 36,
    height: 36,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(251, 191, 36, 0.45)',
    color: '#92400e',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  } satisfies SxProps<Theme>,
  mobileNoticeText: {
    fontSize: 13,
    color: '#92400e',
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  mobileTripFooter: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileTripPrimaryButton: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 16px',
    borderRadius: 1,
    border: 'none',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    fontSize: 14,
    boxShadow: '0 16px 32px rgba(238, 92, 40, 0.24)',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 20px 40px rgba(238, 92, 40, 0.28)',
    },
  } satisfies SxProps<Theme>,
  mobileTripGhostButton: {
    width: 44,
    height: 44,
    borderRadius: radiusTokens.md,
    border: 'none',
    backgroundColor: 'rgba(245, 243, 240, 0.9)',
    color: 'rgba(74, 57, 42, 0.75)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(238, 234, 226, 0.95)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileQuickActionSection: {
    padding: '0 16px 24px',
  } satisfies SxProps<Theme>,
  mobileQuickActionButton: {
    width: '100%',
    borderRadius: 28,
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.sm,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    fontSize: 15,
    border: 'none',
    boxShadow: '0 24px 48px rgba(238, 92, 40, 0.32)',
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 28px 56px rgba(238, 92, 40, 0.38)',
    },
  } satisfies SxProps<Theme>,
  breadcrumbNav: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    fontSize: 13,
    color: 'rgba(90, 68, 51, 0.7)',
  } satisfies SxProps<Theme>,
  breadcrumbLink: {
    cursor: 'pointer',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  pageHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.md,
  } satisfies SxProps<Theme>,
  pageTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: { xs: 32, md: 40 },
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  primaryCta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    padding: '12px 24px',
    borderRadius: radiusTokens.lg,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    boxShadow: '0 18px 42px rgba(238, 92, 40, 0.35)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, background-image 0.2s ease',
    border: 'none',
    cursor: 'pointer',
    '&:hover': {
      transform: 'translateY(-2px) scale(1.02)',
      boxShadow: '0 22px 48px rgba(238, 92, 40, 0.4)',
      backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[600]} 0%, ${colorTokens.safari[700]} 100%)`,
    },
  } satisfies SxProps<Theme>,
  sectionsStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  sectionTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 600,
    fontSize: { xs: 24, md: 28 },
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  tripCard: {

    backgroundColor: 'rgba(255,255,255,0.92)',
    backdropFilter: 'blur(18px)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.4)',
    boxShadow: baseCardShadow,
    overflow: 'hidden',
    transition: 'box-shadow 0.2s ease, transform 0.2s ease',
    '&:hover': {
      boxShadow: '0 28px 72px rgba(61, 48, 36, 0.22)',
      transform: 'translateY(-2px)',
    },
  } satisfies SxProps<Theme>,
  tripCardPending: {
    border: '1px solid rgba(244, 185, 66, 0.6)',
    boxShadow: '0 26px 64px rgba(244, 185, 66, 0.22)',
  } satisfies SxProps<Theme>,
  tripCardPast: {
    opacity: 0.94,
  } satisfies SxProps<Theme>,
  tripCardContent: {
    padding: { xs: spacingTokens.xs, md: spacingTokens.xs },
  } satisfies SxProps<Theme>,
  tripCardHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'flex-start' },
    justifyContent: 'space-between',
    gap: spacingTokens.md,
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tripOverview: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: spacingTokens.md,
  } satisfies SxProps<Theme>,
  tripMedia: {
    width: 150,
    height: 112,
    borderRadius: 1,
    overflow: 'hidden',
    boxShadow: '0 16px 34px rgba(61, 48, 36, 0.24)',
  } satisfies SxProps<Theme>,
  tripMediaImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  tripTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 20,
    fontWeight: 600,
    color: colorTokens.earth[800],
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tripSubtitle: {
    fontSize: 14,
    color: 'rgba(74, 57, 42, 0.65)',
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tripDateRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    color: 'rgba(74, 57, 42, 0.8)',
  } satisfies SxProps<Theme>,
  tripDateIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(238, 92, 40, 0.1)',
    color: colorTokens.safari[600],
  } satisfies SxProps<Theme>,
  tripPriceBlock: {
    textAlign: { xs: 'left', md: 'right' },
  } satisfies SxProps<Theme>,
  tripPrice: {
    fontSize: { xs: 22, md: 26 },
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  tripPriceCaption: {
    fontSize: 12,
    color: 'rgba(90, 68, 51, 0.55)',
    marginBottom: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  statusBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    border: '1px solid transparent',
  } satisfies SxProps<Theme>,
  statusBadgeConfirmed: {
    backgroundImage: 'linear-gradient(135deg, rgba(110,231,183,0.35) 0%, rgba(16,185,129,0.55) 100%)',
    color: '#065f46',
    borderColor: 'rgba(16,185,129,0.45)',
  } satisfies SxProps<Theme>,
  statusBadgePending: {
    backgroundImage: 'linear-gradient(135deg, rgba(253,230,138,0.45) 0%, rgba(245,158,11,0.6) 100%)',
    color: '#92400e',
    borderColor: 'rgba(245,158,11,0.5)',
  } satisfies SxProps<Theme>,
  statusBadgeCompleted: {
    backgroundImage: 'linear-gradient(135deg, rgba(212,196,176,0.45) 0%, rgba(148,137,122,0.5) 100%)',
    color: colorTokens.earth[700],
    borderColor: 'rgba(148,137,122,0.45)',
  } satisfies SxProps<Theme>,
  metaShell: {
    display: 'grid',
    gridTemplateColumns: { xs: 'repeat(1, minmax(0,1fr))', sm: 'repeat(3, minmax(0,1fr))' },
    gap: spacingTokens.md,
    padding: spacingTokens.xs,
    backgroundColor: 'rgba(245, 243, 240, 0.65)',
    borderRadius: 1,
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  metaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  metaLabel: {
    fontSize: 13,
    color: 'rgba(90, 68, 51, 0.6)',
  } satisfies SxProps<Theme>,
  metaValue: {
    fontSize: 15,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  noticeCard: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: spacingTokens.xs,
    backgroundImage: 'linear-gradient(135deg, rgba(253, 230, 138, 0.45) 0%, rgba(251, 191, 36, 0.25) 100%)',
    border: '1px solid rgba(251, 191, 36, 0.5)',
    borderRadius: 1,
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  noticeIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(251, 191, 36, 0.4)',
    color: '#92400e',
  } satisfies SxProps<Theme>,
  noticeBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  noticeTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#92400e',
  } satisfies SxProps<Theme>,
  noticeDescription: {
    fontSize: 12,
    color: '#b45309',
  } satisfies SxProps<Theme>,
  cardFooter: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
    paddingTop: spacingTokens.xs,
    borderTop: '1px solid rgba(214, 198, 178, 0.6)',
  } satisfies SxProps<Theme>,
  cardCtas: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  inlineActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  tertiaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 13,
    fontWeight: 600,
    color: 'rgba(74, 57, 42, 0.75)',
    cursor: 'pointer',
    transition: 'color 0.2s ease',
    textDecoration: 'none',
    border: 'none',
    background: 'none',
    padding: 0,
    '&:hover': {
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  primaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 18px',
    borderRadius: radiusTokens.md,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    fontSize: 14,
    boxShadow: '0 16px 36px rgba(238, 92, 40, 0.32)',
    border: 'none',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease, background-image 0.2s ease',
    '&:hover': {
      transform: 'translateY(-1px) scale(1.01)',
      boxShadow: '0 20px 42px rgba(238, 92, 40, 0.36)',
      backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[600]} 0%, ${colorTokens.safari[700]} 100%)`,
    },
  } satisfies SxProps<Theme>,
  secondaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '9px 18px',
    borderRadius: radiusTokens.md,
    border: '1px solid rgba(214, 198, 178, 0.65)',
    color: 'rgba(74, 57, 42, 0.8)',
    fontWeight: 600,
    fontSize: 14,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    textDecoration: 'none',
    transition: 'border-color 0.2s ease, background-color 0.2s ease, color 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(245, 243, 240, 0.8)',
      borderColor: 'rgba(214, 198, 178, 0.9)',
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  tripboardGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: 'repeat(1, minmax(0,1fr))', md: 'repeat(2, minmax(0,1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tripboardCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    backdropFilter: 'blur(14px)',
    borderRadius: 2,
    border: '1px solid rgba(214, 198, 178, 0.4)',
    padding: spacingTokens.xs,
    boxShadow: baseCardShadow,
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    cursor: 'pointer',
    '&:hover': {
      transform: 'translateY(-3px) scale(1.01)',
      boxShadow: '0 28px 72px rgba(61, 48, 36, 0.2)',
    },
  } satisfies SxProps<Theme>,
  tripboardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  tripboardTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: 18,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  tripboardIconWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.xs,
    borderRadius: 1,
  } satisfies SxProps<Theme>,
  tripboardMeta: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: 'rgba(74, 57, 42, 0.7)',
    marginBottom: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  collaboratorGroup: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: spacingTokens.xs,
    '& > *:not(:first-of-type)': {
      marginLeft: -spacingTokens.xs,
    },
  } satisfies SxProps<Theme>,
  collaboratorAvatar: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    border: '2px solid white',
    boxShadow: '0 8px 16px rgba(61, 48, 36, 0.18)',
  } satisfies SxProps<Theme>,
  collaboratorPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    border: '2px solid white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundImage: 'linear-gradient(135deg, rgba(214, 198, 178, 0.45) 0%, rgba(214, 198, 178, 0.7) 100%)',
    color: 'rgba(74, 57, 42, 0.8)',
    fontSize: 12,
    fontWeight: 600,
    boxShadow: '0 8px 16px rgba(61, 48, 36, 0.18)',
  } satisfies SxProps<Theme>,
  tripboardLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.safari[600],
    cursor: 'pointer',
    textDecoration: 'none',
    border: 'none',
    background: 'none',
    padding: 0,
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colorTokens.safari[700],
    },
  } satisfies SxProps<Theme>,
} as const;
