import type { SxProps, Theme } from '@mui/material/styles';

import { colorTokens, radiusTokens, spacingTokens, typographyTokens } from './tokens';

const recommendationsPageStyles = {
  main: {
    role: 'main',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(140deg, ${colorTokens.neutral[50]} 0%, rgba(244, 185, 66, 0.18) 100%)`,
  } satisfies SxProps<Theme>,
  mobilePage: {
    display: { xs: 'flex', md: 'none' },
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundImage: `linear-gradient(150deg, ${colorTokens.neutral[50]} 0%, rgba(252, 244, 230, 0.92) 32%, rgba(249, 235, 210, 0.88) 100%)`,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobileHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: 'rgba(255,255,255,0.95)',
    backdropFilter: 'blur(14px)',
    borderBottom: '1px solid rgba(210, 195, 176, 0.45)',
    boxShadow: '0 16px 32px rgba(61, 48, 36, 0.12)',
  } satisfies SxProps<Theme>,
  mobileHeaderBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacingTokens.sm,
    borderRadius: radiusTokens.md,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    boxShadow: '0 18px 36px rgba(238, 92, 40, 0.28)',
  } satisfies SxProps<Theme>,
  mobileHeaderTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 20,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.earth[800]} 0%, ${colorTokens.safari[700]} 85%)`,
    WebkitBackgroundClip: 'text',
    color: 'transparent',
  } satisfies SxProps<Theme>,
  mobileHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileHeaderButton: {
    width: 40,
    height: 40,
    border: 'none',
    borderRadius: radiusTokens.md,
    backgroundColor: 'transparent',
    color: 'rgba(74,57,42,0.75)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(245,243,240,0.85)',
      transform: 'translateY(-1px)',
    },
  } satisfies SxProps<Theme>,
  mobileHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '2px solid rgba(238, 92, 40, 0.25)',
    boxShadow: '0 16px 32px rgba(61, 48, 36, 0.16)',
  } satisfies SxProps<Theme>,
  mobileMain: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    backgroundImage: `linear-gradient(145deg, rgba(248, 245, 235, 0.85) 0%, rgba(255, 247, 229, 0.92) 100%)`,
  } satisfies SxProps<Theme>,
  mobileHeroSection: {
    position: 'relative',
    height: 210,
    overflow: 'hidden',
    borderBottomLeftRadius: radiusTokens.lg,
    borderBottomRightRadius: radiusTokens.lg,
  } satisfies SxProps<Theme>,
  mobileHeroMedia: {
    position: 'absolute',
    inset: 0,
  } satisfies SxProps<Theme>,
  mobileHeroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobileHeroOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(115deg, rgba(0,0,0,0.68) 0%, rgba(0,0,0,0.35) 60%, rgba(0,0,0,0.12) 100%)',
  } satisfies SxProps<Theme>,
  mobileHeroContent: {
    position: 'relative',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '0 18px',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileHeroTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 28,
    lineHeight: 1.15,
  } satisfies SxProps<Theme>,
  mobileHeroDescription: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.88)',
  } satisfies SxProps<Theme>,
  mobileHeroHighlights: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileHeroHighlight: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '8px 14px',
    borderRadius: radiusTokens.lg,
    backgroundColor: 'rgba(255,255,255,0.18)',
    backdropFilter: 'blur(10px)',
    fontSize: 12,
    fontWeight: 600,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileWizardSection: {
    padding: '24px 16px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileProgressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 12,
    color: 'rgba(87, 69, 54, 0.65)',
  } satisfies SxProps<Theme>,
  mobileProgressSteps: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileProgressStep: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileProgressNode: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 600,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.24)',
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  mobileProgressNodeCompleted: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileProgressNodeActive: {
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    border: `2px solid ${colorTokens.safari[500]}`,
  } satisfies SxProps<Theme>,
  mobileProgressNodeUpcoming: {
    backgroundColor: 'rgba(210,195,176,0.45)',
    color: 'rgba(74,57,42,0.65)',
  } satisfies SxProps<Theme>,
  mobileProgressLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  mobileProgressConnector: {
    width: 48,
    height: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(210,195,176,0.45)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  mobileProgressConnectorFilled: {
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileProgressConnectorPartial: {
    width: '55%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  mobileSummaryCard: {
    backgroundImage: 'linear-gradient(135deg, rgba(255, 255, 255, 0.9) 0%, rgba(255, 247, 236, 0.92) 100%)',
    borderRadius: 2 ,
    border: '1px solid rgba(214,198,178,0.4)',
    padding: 5,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    boxShadow: '0 24px 48px rgba(61, 48, 36, 0.14)',
  } satisfies SxProps<Theme>,
  mobileSummaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileSummaryItem: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 1,
    border: '1px solid rgba(210,195,176,0.35)',
    padding: spacingTokens.xs,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  } satisfies SxProps<Theme>,
  mobileSummaryLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: colorTokens.safari[600],
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  } satisfies SxProps<Theme>,
  mobileSummaryValue: {
    fontSize: 13,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  mobileFilterCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.4)',
    boxShadow: '0 20px 44px rgba(61, 48, 36, 0.12)',
    padding: 5,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileFilterHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileFilterControls: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileFilterRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobileFilterSelect: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.95)',
    fontSize: 13,
    fontWeight: 500,
    color: colorTokens.earth[700],
    appearance: 'none',
  } satisfies SxProps<Theme>,
  mobileFilterButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 14px',
    borderRadius: 16,
    border: 'none',
    backgroundColor: 'rgba(255,244,236,0.95)',
    color: colorTokens.safari[700],
    fontWeight: 600,
    fontSize: 13,
  } satisfies SxProps<Theme>,
  mobilePackageList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    padding: '0 16px 0',
  } satisfies SxProps<Theme>,
  mobilePackageCard: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.4)',
    boxShadow: '0 28px 52px rgba(61, 48, 36, 0.14)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePackageMedia: {
    position: 'relative',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobilePackageImage: {
    width: '100%',
    height: 190,
    borderRadius: 1,
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobilePackageGallery: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePackageGalleryImage: {
    width: '100%',
    height: 72,
    borderRadius:1,
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  mobilePackageGalleryMore: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 1,
    backgroundColor: 'rgba(245, 240, 235, 0.9)',
    color: 'rgba(74,57,42,0.7)',
    fontSize: 12,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  mobilePackageBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '6px 12px',
    borderRadius: radiusTokens.pill,
    color: colorTokens.neutral.white,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    boxShadow: '0 16px 30px rgba(0,0,0,0.18)',
  } satisfies SxProps<Theme>,
  mobilePackageSaveButton: {
    position: 'absolute',
    top: spacingTokens.sm,
    right: spacingTokens.sm,
    width: 40,
    height: 40,
    borderRadius: '50%',
    border: 'none',
    backgroundColor: 'rgba(255,255,255,0.9)',
    backdropFilter: 'blur(6px)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 12px 24px rgba(61, 48, 36, 0.18)',
  } satisfies SxProps<Theme>,
  mobilePackageBody: {
    padding: '0 16px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobilePackageTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: 20,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  mobilePackageDescription: {
    fontSize: 13,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  mobilePackageRating: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 12,
    color: 'rgba(74,57,42,0.65)',
  } satisfies SxProps<Theme>,
  mobilePackageMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    fontSize: 12,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  mobilePackagePriceBlock: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    color: colorTokens.safari[600],
  } satisfies SxProps<Theme>,
  mobilePackageHighlights: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: spacingTokens.xs,
    fontSize: 12,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  mobilePackageHighlight: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePackageDestinations: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 12,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  mobilePackageDestination: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  mobilePackageActions: {
    display: 'flex',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  mobileSecondaryButton: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 14px',
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: 'rgba(255,255,255,0.95)',
    color: colorTokens.safari[600],
    fontWeight: 600,
    fontSize: 13,
  } satisfies SxProps<Theme>,
  mobilePrimaryButton: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacingTokens.xs,
    padding: '12px 16px',
    borderRadius: 1,
    border: 'none',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    fontSize: 13,
    boxShadow: '0 18px 32px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
  mobileLoadMore: {
    padding: '32px 16px 48px',
    display: 'flex',
    justifyContent: 'center',
  } satisfies SxProps<Theme>,
  mobileLoadMoreButton: {
    padding: '24px 24px',
    borderRadius: 1,
    border: '1px solid rgba(214,198,178,0.6)',
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    fontWeight: 600,
    fontSize: 13,
    boxShadow: '0 18px 32px rgba(61, 48, 36, 0.12)',
  } satisfies SxProps<Theme>,
  heroSection: {
    position: 'relative',
    height: { xs: 440, md: 320 },
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  heroMediaWrap: {
    position: 'absolute',
    inset: 0,
  } satisfies SxProps<Theme>,
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundImage:
      'linear-gradient(115deg, rgba(0,0,0,0.72) 0%, rgba(0,0,0,0.45) 48%, rgba(0,0,0,0.12) 100%)',
  } satisfies SxProps<Theme>,
  heroContentWrap: {
    position: 'relative',
    height: '100%',
    maxWidth: 1120,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    alignItems: 'center',
  } satisfies SxProps<Theme>,
  heroCopy: {
    maxWidth: { xs: '100%', md: 640 },
    color: colorTokens.neutral.white,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  heroTitle: {
    fontFamily: typographyTokens.heading,
    fontWeight: 700,
    fontSize: { xs: 36, md: 50 },
    lineHeight: 1.05,
  } satisfies SxProps<Theme>,
  heroDescription: {
    fontSize: { xs: 18, md: 20 },
    color: 'rgba(255,255,255,0.9)',
  } satisfies SxProps<Theme>,
  heroHighlights: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  heroHighlight: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 18px',
    borderRadius: radiusTokens.pill,
    backgroundColor: 'rgba(255,255,255,0.22)',
    backdropFilter: 'blur(12px)',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.neutral.white,
  } satisfies SxProps<Theme>,
  wizardSection: {
    padding: { xs: '48px 0', md: '64px 0' },
  } satisfies SxProps<Theme>,
  wizardContainer: {
    maxWidth: 1040,
    margin: '0 auto',
    padding: { xs: '0 24px', md: '0 32px' },
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  progressHeader: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressSteps: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  progressStep: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  stepWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  progressNode: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 600,
    color: colorTokens.neutral.white,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.28)',
  } satisfies SxProps<Theme>,
  progressNodeCompleted: {
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  progressNodeActive: {
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    border: `2px solid ${colorTokens.safari[400]}`,
    boxShadow: '0 12px 28px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
  progressLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  progressLabelActive: {
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  progressLabelCompleted: {
    color: colorTokens.safari[700],
  } satisfies SxProps<Theme>,
  progressConnector: {
    width: 72,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(210, 195, 176, 0.55)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  progressConnectorFilled: {
    width: '100%',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[400]} 0%, ${colorTokens.safari[600]} 100%)`,
  } satisfies SxProps<Theme>,
  summaryCard: {
    backgroundImage: 'linear-gradient(135deg, rgba(255, 255, 255, 0.85) 0%, rgba(255,255,255,0.95) 100%)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.35)',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    backdropFilter: 'blur(18px)',
  } satisfies SxProps<Theme>,
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))', md: 'repeat(4, minmax(0, 1fr))' },
    gap: spacingTokens.md,
  } satisfies SxProps<Theme>,
  summaryLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: colorTokens.safari[600],
  } satisfies SxProps<Theme>,
  summaryValue: {
    fontSize: 14,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  filterCard: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.4)',
    boxShadow: '0 28px 56px rgba(61, 48, 36, 0.14)',
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  filterHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  filterControls: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  filterSelect: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    padding: '12px 16px',
    borderRadius: 1,
    border: '1px solid rgba(214, 198, 178, 0.75)',
    backgroundColor: 'rgba(255,255,255,0.96)',
    fontSize: 13,
    fontWeight: 500,
    color: colorTokens.earth[700],
    cursor: 'pointer',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    outline: 'none',
    '&:focus-visible': {
      borderColor: colorTokens.safari[400],
      boxShadow: '0 0 0 3px rgba(238, 92, 40, 0.18)',
    },
  } satisfies SxProps<Theme>,
  filterTrigger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 18px',
    borderRadius: 1,
    backgroundColor: 'rgba(238, 92, 40, 0.08)',
    color: colorTokens.safari[700],
    fontSize: 13,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  packageList: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  packageCard: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 2,
    border: '1px solid rgba(210,195,176,0.4)',
    boxShadow: '0 36px 72px rgba(61, 48, 36, 0.18)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    transition: 'box-shadow 0.25s ease, transform 0.25s ease',
    '&:hover': {
      boxShadow: '0 48px 96px rgba(61, 48, 36, 0.22)',
      transform: 'translateY(-2px)',
    },
  } satisfies SxProps<Theme>,
  packageMedia: {
    position: 'relative',
    padding: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  packageBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    padding: '6px 14px',
    borderRadius: 1,
    fontSize: 12,
    fontWeight: 600,
    color: colorTokens.neutral.white,
    boxShadow: '0 12px 28px rgba(15, 118, 110, 0.4)',
  } satisfies SxProps<Theme>,
  packageSaveButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.88)',
    color: 'rgba(74,57,42,0.65)',
    boxShadow: '0 8px 18px rgba(61, 48, 36, 0.16)',
    transition: 'background-color 0.2s ease, color 0.2s ease',
  } satisfies SxProps<Theme>,
  packageGallery: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, minmax(0, 1fr))' },
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  galleryPrimary: {
    gridColumn: { xs: 'auto', md: 'span 1' },
    borderRadius: 1,
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  galleryPrimaryImage: {
    width: '100%',
    height: { xs: 220, md: 260 },
    objectFit: 'cover',
    borderRadius: 1,
  } satisfies SxProps<Theme>,
  gallerySecondary: {
    gridColumn: { xs: 'auto', md: 'span 2' },
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  galleryThumb: {
    width: '100%',
    height: 120,
    objectFit: 'cover',
    borderRadius: 1,
  } satisfies SxProps<Theme>,
  galleryPlaceholder: {
    borderRadius: 1,
    backgroundColor: 'rgba(231, 229, 221, 0.75)',
    color: 'rgba(74,57,42,0.6)',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } satisfies SxProps<Theme>,
  packageContent: {
    padding: spacingTokens.sm,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  packageHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  packageTitle: {
    fontFamily: typographyTokens.heading,
    fontSize: { xs: 28, md: 32 },
    fontWeight: 700,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  packageDescription: {
    fontSize: 14,
    color: 'rgba(74,57,42,0.7)',
    maxWidth: 720,
  } satisfies SxProps<Theme>,
  ratingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacingTokens.sm,
    flexWrap: 'wrap',
  } satisfies SxProps<Theme>,
  statItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: 'rgba(74,57,42,0.7)',
  } satisfies SxProps<Theme>,
  priceStack: {
    textAlign: 'right',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 140,
  } satisfies SxProps<Theme>,
  priceValue: {
    fontSize: 32,
    fontWeight: 700,
    color: colorTokens.safari[600],
  } satisfies SxProps<Theme>,
  sectionGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, minmax(0, 1fr))' },
    gap: spacingTokens.lg,
  } satisfies SxProps<Theme>,
  sectionBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  sectionHeading: {
    fontSize: 16,
    fontWeight: 600,
    color: colorTokens.earth[800],
  } satisfies SxProps<Theme>,
  bulletList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
    fontSize: 13,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  destinationPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 14px',
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(238, 92, 40, 0.08)',
    color: colorTokens.safari[700],
    fontSize: 13,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  packageFooter: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: spacingTokens.sm,
    paddingTop: spacingTokens.sm,
    borderTop: '1px solid rgba(210,195,176,0.45)',
  } satisfies SxProps<Theme>,
  footerActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  footerPrimaryActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
    justifyContent: 'flex-end',
  } satisfies SxProps<Theme>,
  tertiaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 16px',
    borderRadius: 16,
    backgroundColor: 'transparent',
    color: 'rgba(74,57,42,0.7)',
    fontSize: 13,
    fontWeight: 600,
  } satisfies SxProps<Theme>,
  secondaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 22px',
    borderRadius: 18,
    border: `1px solid ${colorTokens.safari[300]}`,
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    fontWeight: 600,
    boxShadow: '0 12px 24px rgba(238, 92, 40, 0.14)',
  } satisfies SxProps<Theme>,
  primaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '12px 28px',
    borderRadius: 20,
    backgroundImage: `linear-gradient(135deg, ${colorTokens.safari[500]} 0%, ${colorTokens.safari[600]} 100%)`,
    color: colorTokens.neutral.white,
    fontWeight: 600,
    boxShadow: '0 18px 36px rgba(238, 92, 40, 0.24)',
  } satisfies SxProps<Theme>,
  recommendationBanner: {
    position: 'relative',
    marginTop: spacingTokens.xs,
    borderRadius: 2,
    padding: spacingTokens.sm,
    backgroundImage: 'linear-gradient(135deg, rgba(34, 197, 94, 0.18) 0%, rgba(59, 130, 246, 0.18) 100%)',
    border: '1px solid rgba(34,197,94,0.25)',
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  bannerContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacingTokens.xs,
  } satisfies SxProps<Theme>,
  bannerActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacingTokens.sm,
  } satisfies SxProps<Theme>,
  bannerButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacingTokens.xs,
    padding: '10px 18px',
    borderRadius: 1,
    backgroundColor: colorTokens.neutral.white,
    color: colorTokens.safari[600],
    fontWeight: 600,
    boxShadow: '0 12px 24px rgba(59, 130, 246, 0.18)',
  } satisfies SxProps<Theme>,
} as const;

export default recommendationsPageStyles;
