import type { SxProps, Theme } from '@mui/material/styles';

import { colorTokens, radiusTokens } from './tokens';

export const topBarStyles = {
  appBar: {
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.92)',
    backdropFilter: 'blur(18px)',
    borderBottom: '1px solid rgba(92, 63, 51, 0.08)',
    boxShadow: '0 12px 30px rgba(32, 25, 19, 0.12)',
  } satisfies SxProps<Theme>,
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    width: '100%',
    px: { xs: 2, md: 4 },
  } satisfies SxProps<Theme>,
  logoText: {
    fontFamily: '"Playfair Display", serif',
    fontWeight: 700,
    background: 'linear-gradient(90deg, #3d3024 0%, #73261c 100%)',
    WebkitBackgroundClip: 'text',
    color: 'transparent',
    letterSpacing: '-0.01em',
  } satisfies SxProps<Theme>,
  searchPaper: {
    position: 'relative',
    maxWidth: 600,
    flex: 1,
    borderRadius: radiusTokens.md,
    backgroundColor: 'rgba(255,255,255,0.9)',
    border: '1px solid rgba(212,200,186,0.6)',
    display: 'flex',
    alignItems: 'center',
    px: 2,
    py: 0.5,
    boxShadow: '0 16px 30px rgba(74, 57, 42, 0.08)',
  } satisfies SxProps<Theme>,
  searchIcon: {
    position: 'absolute',
    left: 18,
    width: 16,
    height: 16,
    opacity: 0.6,
  } satisfies SxProps<Theme>,
  searchInput: {
    pl: 10,
    pr: 2,
    py: 1.5,
    fontSize: 14,
    fontWeight: 500,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  navStack: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
  } satisfies SxProps<Theme>,
  localeToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 2,
    py: 1,
    borderRadius: radiusTokens.md,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: 'rgba(92, 63, 51, 0.08)',
    },
  } satisfies SxProps<Theme>,
  flagGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
  } satisfies SxProps<Theme>,
  flagIcon: {
    width: 26,
    height: 18,
    borderRadius: .2,
    overflow: 'hidden',
    boxShadow: '0 3px 8px rgba(47, 176, 63, 0.25)',
    border: '1px solid rgba(0, 0, 0, 0.06)',
    objectFit: 'cover',
  } satisfies SxProps<Theme>,
  localeLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  chevronIcon: {
    width: 12,
    height: 12,
    opacity: 0.6,
  } satisfies SxProps<Theme>,
  currencyToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 2,
    py: 1,
    borderRadius: radiusTokens.md,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    color: colorTokens.earth[700],
    fontSize: 14,
    fontWeight: 500,
    '&:hover': {
      backgroundColor: 'rgba(92, 63, 51, 0.08)',
    },
  } satisfies SxProps<Theme>,
  currencyLabel: {
    fontSize: 14,
    fontWeight: 600,
    color: colorTokens.earth[700],
  } satisfies SxProps<Theme>,
  quickLink: {
    fontSize: 14,
    fontWeight: 500,
    color: colorTokens.earth[600],
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  savedButton: {
    position: 'relative',
    fontSize: 14,
    fontWeight: 500,
    color: colorTokens.earth[600],
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 0.5,
    transition: 'color 0.2s ease',
    '&:hover': {
      color: colorTokens.safari[600],
    },
  } satisfies SxProps<Theme>,
  savedIcon: {
    width: 16,
    height: 16,
  } satisfies SxProps<Theme>,
  avatarRing: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    overflow: 'hidden',
    border: '2px solid rgba(238, 92, 40, 0.25)',
    transition: 'border-color 0.2s ease, transform 0.2s ease',
    cursor: 'pointer',
    '&:hover': {
      borderColor: colorTokens.safari[500],
      transform: 'scale(1.03)',
    },
  } satisfies SxProps<Theme>,
  navLink: (isActive: boolean) => ({
    fontWeight: isActive ? 600 : 500,
    color: isActive ? colorTokens.safari[700] : colorTokens.earth[500],
    textDecoration: 'none',
    transition: 'color 0.2s ease',
  }),
};
